version: "3.8"

volumes:
        nest_volume: 
                name: nest_volume
                driver: local
                driver_opts: 
                        type: none
                        o: bind
                        device: ${PWD}/DockerFiles/nestjs/src

services:
        nest:
                container_name: nest
                image: nest
                build: ./DockerFiles/nestjs/
                restart: on-failure
                ports:
                        - 3000:3000
                volumes:
                        - nest_volume:/root/backend/src/
