version: "3.8"

volumes:
        nest_volumes: 
                name: nest_volumes
                driver: local
                driver_opts: 
                        type: none
                        o: bind
                        device: /nfs/homes/$USER/stud/Transcendence/Dockerfiles/nestjs/src

services:
        nest:
                container_name: nest
                image: nest
                build: ./DockerFiles/nestjs/
                restart: on-failure
                ports:
                        - 3000:3000
                volumes:
                        - trans_volumes:/root/backend/src/
