export enum errorMessages
{
	MISSING = "Missing code or state parameter !",
	DIFFERENT = "State received differ from state generated by the server !",
	INVALIDARG = "The value for one of the fields in the request was invalid !",
	NONAME = "Parameter name is missing !",
	ALREADYTAKEN = "This user name is already taken !",
	ALREADYREGISTER = "You have already set your name !",
	CODEINVALID = "The code sent has already been used !",
	MISSINGNAME = "No name specified in the request !",
	NOTREGISTERED = "Socket is not registered !",
	INVALIDNAME = "The user requested dont exist !",
	YOUAREIGNORED = "This user and you cannot interact !",
	ALREADYFRIEND = "This user and you are already friends !",
	NOREQUEST = "This user didn't asked to be your friend !",
	NOTFRIEND = "This user and you arn't friend !",
	NOTIGNORED = "You dont ignore this user !",
}

export enum urls
{
	TOKEN = "https://api.intra.42.fr/oauth/token",
	URI = "http://localhost:3000",
	ORIGIN = "http://localhost:3000",
	ME = "https://api.intra.42.fr/v2/me",
}
