export enum errorMessages
{
//=====				System				=====

	MISSING = "Missing code or state parameter !",
	HASHFAIL = "Filed to hash the token, please try again !",
	DIFFERENT = "State received differ from state generated by the server !",
	INVALIDARG = "The value for one of the fields in the request was invalid !",
	INVALIDUSER = "User that made the request dont exist in database !",
	INVALIDIMAGE = "Avatar must be to format png or jpeg and be less than 1.5 mB !",
	INVALIDCODE = "Code provided is invalid or expired !",
	CANTSAVE = "Error while saving file !",
	ALREADYTAKEN = "This user name is already taken !",
	MISSINGNAME = "No name specified in the request !",
	NOTREGISTERED = "Socket is not registered !",
	APIFAIL = "Request to 42 API failed, please try again !",
	CREATEFAIL = "Failed to create user, please try again !",
	DBFAIL = "Failed to get database object, please try again !",
	ALREADYMM = "You already join the queue !",
	INGAME = "You can\'t join the queue when you are in game !",
	NOTAPLAYER = "You are not a player of this game stop lying !",
	MISSINGURI = "No URI specified in env please contatc a server administrator !",
	INVALID2FA = "Invalid 2FA token",
	INVALIDTOKEN = "Invalid bearer token",
	USERNOTREGISTERED = "User not registered",
	MISSINGUSER = "Invalid user",


//=====				Relation			=====

	INVALIDNAME = "The user requested dont exist !",
	YOUAREIGNORED = "This user blocked you !",
	ALREADYFRIEND = "This user and you are already friends !",
	ALREADYIGNORED = "You already ignored this user !",
	NOREQUEST = "This user didn't asked to be your friend !",
	NOTFRIEND = "This user and you arn't friend !",
	NOTIGNORED = "You dont ignore this user !",
	REQUESTTOIGNORE = "You cant send a friend request to an user you blocked !",
	MESSAGETOIGNORE = "You cant send a message to an user you blocked !",
	ACCEPTTOIGNORE = "You cant accept friend request from blocked user !",
	ALREADYREQUESTED = "You already sent a friend request to this user !",
	YOUARECRINGE = "Stop that, you are cringe :/",
	SOSFRIEND = "You can contact S.O.S Amitié at this phone number : 09.72.39.40.50 :)",
	ALREADYACTIVATE = "The 2FA login method has already been activate !",

//=====				Channel				=====

	CHANNELALREADYEXIST = "This channel name is already used !",
	PRIVATEORPASSWORD = "You cant specify a password when creating a private channel !",
	CANTINVITEONPUBLIC = "You cant invite user in public channel !",
	CHANNELDONTEXIST = "The channel specified dont exist !",
	ALREADYADMIN = "This user is already an adminstrator of this channel !",
	NOTANADMINISTRATOR = "This user is not an administrator of this channel !",
	NOTINTHISCHANNEL = "This user is not in this channel !",
	ALREADYINCHANNEL = "You are already in this channel !",
	USERALREADYINCHANNEL = "This user is already in this channel !",
	ALREADYINVITED = "This user is already invited in this channel !",
	NOTJOINED = "You are not in this channel !",
	INCORRECTPASSWORD = "The password provided dont match !",
	NOTONTHELIST = "You are not invited to join this channel !",
	NOTTHEOWNER = "Only the owner of this channel can do this operation !",
	NOTOP = "Only an administrator or the owner of this channel can do this operation !",
	NOTINVITED = "This user wasnt invited to this channel !",
	NOTBAN = "This user isn't ban from this channel !",
	NOTMUTE = "This user isn't mute in this channel !",
	ACAPTAINDONTLEAVEHISSHIP = "You are the owner of this channel you can't leave it !",
	CANTDEMOTEOWNER = "You cant demote the owner of this channel !",
	CANTSANCTIONOWNER = "You cant sanction the mighty owner of this channel !",
	CANTSANCTIONEQUAL = "This user's power is equal to yours, you cannot defeat him !",
	YOUAREBAN = "You are ban from this channel !",
	YOUAREMUTE = "You are mute in this channel !",
	ALREADYBAN = "This user is already ban from this channel !",
	ALREADYMUTE = "This user is already mute from this channel !",
	INCORRECTVISIBILITY = "You can\'t set a password in a private channel",
}

export enum urls
{
	TOKEN = "https://api.intra.42.fr/oauth/token",
	ME = "https://api.intra.42.fr/v2/me",
}

